In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import wavfile
from scipy.signal import spectrogram
import os
import librosa
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from pydub import AudioSegment
import joblib
import sounddevice as sd
import soundfile as sf
import scipy.io.wavfile as wav

C:\Users\berka\anaconda3\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


In [40]:
pip install librosa matplotlib numpy scipy

Note: you may need to restart the kernel to use updated packages.


In [107]:
pip install sounddevice numpy librosa

   ---------------------------------------- 0.0/363.6 kB ? eta -:--:--
   - -------------------------------------- 10.2/363.6 kB ? eta -:--:--
   --- ----------------------------------- 30.7/363.6 kB 435.7 kB/s eta 0:00:01
   ------ -------------------------------- 61.4/363.6 kB 409.6 kB/s eta 0:00:01
   --------- ----------------------------- 92.2/363.6 kB 521.8 kB/s eta 0:00:01
   ---------------- --------------------- 153.6/363.6 kB 654.6 kB/s eta 0:00:01
   ----------------------- -------------- 225.3/363.6 kB 808.4 kB/s eta 0:00:01
   -------------------------------- ----- 307.2/363.6 kB 948.8 kB/s eta 0:00:01
   ----------------------------------- -- 337.9/363.6 kB 910.2 kB/s eta 0:00:01
   -------------------------------------  358.4/363.6 kB 928.4 kB/s eta 0:00:01
   -------------------------------------- 363.6/363.6 kB 806.8 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


# WAV dosyalarını 1.5 saniyelik dosyalara ayırma

In [7]:
# WAV dosyalarının bulunduğu dizin
wav_folder = 'ses_dosyalari/' 
# 1.5 saniyelik kayıtlara bölünmüş WAV dosyalarının bulunduğu dizin
new_wav_folder = 'ses_dosyalari/new_wav_folder'

# 1.5 saniyeyi milisaniyeye çevir
segment_duration = 1.5 * 1000  

# Klasördeki tüm WAV dosyalarını işle
for filename in os.listdir(wav_folder):
    if filename.endswith(".wav"):
        input_path = os.path.join(wav_folder, filename)
        audio = AudioSegment.from_wav(input_path)
        total_duration = len(audio)

        # Her WAV dosyasını 1.5 saniyelik parçalara ayır
        for i in range(0, total_duration, int(segment_duration)):
            segment = audio[i:i + int(segment_duration)]
            segment_name = f"{new_wav_folder}/{filename[:-4]}_parca_{i // int(segment_duration)}.wav"
            segment.export(segment_name, format="wav")
            print(f"{segment_name} kaydedildi.")


ses_dosyalari/new_wav_folder/berkay_parca_0.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_1.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_2.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_3.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_4.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_5.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_6.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_7.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_8.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_9.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_10.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_11.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_12.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_13.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_14.wav kaydedildi.
ses_dosyalari/new_wav_folder/berkay_parca_15.wav kaydedildi.
ses_dosyalari/new_wav_folder/berka

In [21]:
# Wav dosyalarının dizinini kontrol etme
audio_file_path = 'ses_dosyalari/new_wav_folder'
for file in os.listdir(audio_file_path):
    print(file)

berkay_parca_0.wav
berkay_parca_1.wav
berkay_parca_10.wav
berkay_parca_11.wav
berkay_parca_12.wav
berkay_parca_13.wav
berkay_parca_14.wav
berkay_parca_15.wav
berkay_parca_16.wav
berkay_parca_17.wav
berkay_parca_18.wav
berkay_parca_19.wav
berkay_parca_2.wav
berkay_parca_20.wav
berkay_parca_21.wav
berkay_parca_22.wav
berkay_parca_23.wav
berkay_parca_24.wav
berkay_parca_25.wav
berkay_parca_26.wav
berkay_parca_27.wav
berkay_parca_28.wav
berkay_parca_29.wav
berkay_parca_3.wav
berkay_parca_30.wav
berkay_parca_31.wav
berkay_parca_32.wav
berkay_parca_33.wav
berkay_parca_34.wav
berkay_parca_35.wav
berkay_parca_36.wav
berkay_parca_4.wav
berkay_parca_5.wav
berkay_parca_6.wav
berkay_parca_7.wav
berkay_parca_8.wav
berkay_parca_9.wav
ekin_parca_0.wav
ekin_parca_1.wav
ekin_parca_10.wav
ekin_parca_11.wav
ekin_parca_12.wav
ekin_parca_13.wav
ekin_parca_14.wav
ekin_parca_15.wav
ekin_parca_16.wav
ekin_parca_17.wav
ekin_parca_18.wav
ekin_parca_19.wav
ekin_parca_2.wav
ekin_parca_20.wav
ekin_parca_21.wav
eki

In [29]:
# Librosa kullanarak örnek ses okuma
audio_file_path = 'ses_dosyalari/new_wav_folder/berkay_parca_5.wav'
librosa_audio_data,librosa_sample_rate = librosa.load(audio_file_path)

print(librosa_audio_data)

[ 0.00093454 -0.00080527 -0.00349255 ... -0.01823891 -0.01040838
 -0.02122949]


In [31]:
# Librosa kullanarak bir ses sinyalinin MFCC özelliklerini çıkarma
mfccs = librosa.feature.mfcc(y=librosa_audio_data, sr=librosa_sample_rate, n_mfcc=128)
print(mfccs.shape)

(128, 65)


# Ses dosyalarını CSV formatına çevirme.

In [9]:
# Ses dosyalarının bulunduğu dizin
audio_directory = 'ses_dosyalari/new_wav_folder'  

# Liste oluşturma
data = []

# Dizin içindeki ses dosyalarını okuma
for file in os.listdir(audio_directory):
    if file.endswith('.wav'):  # Sadece WAV dosyalarını al
        # Dosya adı ve etiket çıkarma
        label = file.split('_')[0]  # Örneğin: 'speaker1' veya 'car' gibi
        file_path = os.path.join(audio_directory, file)  # Tam dosya yolunu oluştur
        data.append({'file_name': file, 'label': label, 'file_path': file_path})

# DataFrame oluşturma
metadata_df = pd.DataFrame(data)

# CSV dosyasını kaydetme
metadata_df.to_csv('ses_metadata.csv', index=False)

# Oluşturulan CSV dosyasını kontrol etme
print(metadata_df)

                file_name   label  \
0      berkay_parca_0.wav  berkay   
1      berkay_parca_1.wav  berkay   
2     berkay_parca_10.wav  berkay   
3    berkay_parca_100.wav  berkay   
4    berkay_parca_101.wav  berkay   
..                    ...     ...   
831    hakan_parca_95.wav   hakan   
832    hakan_parca_96.wav   hakan   
833    hakan_parca_97.wav   hakan   
834    hakan_parca_98.wav   hakan   
835    hakan_parca_99.wav   hakan   

                                             file_path  
0      ses_dosyalari/new_wav_folder\berkay_parca_0.wav  
1      ses_dosyalari/new_wav_folder\berkay_parca_1.wav  
2     ses_dosyalari/new_wav_folder\berkay_parca_10.wav  
3    ses_dosyalari/new_wav_folder\berkay_parca_100.wav  
4    ses_dosyalari/new_wav_folder\berkay_parca_101.wav  
..                                                 ...  
831    ses_dosyalari/new_wav_folder\hakan_parca_95.wav  
832    ses_dosyalari/new_wav_folder\hakan_parca_96.wav  
833    ses_dosyalari/new_wav_folder\hakan_

# Her ses dosyası için MFCC çıkarma.

In [11]:
# CSV dosyasını oku
metadata=pd.read_csv('ses_metadata.csv')

In [13]:
# Ses dosyasını al ve MFCC özelliklerini çıkar.
def features_extractor(file):
    audio, sample_rate = librosa.load(file, sr=None)
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=128)
    mfccs_scaled_features = np.mean(mfccs_features.T, axis=0)
    return mfccs_scaled_features

In [15]:
# Her bir ses dosyasından özellikleri ve sınıf etiketlerini çıkar.
extracted_features = []
for index_num, row in tqdm(metadata.iterrows(), total=metadata.shape[0]):
    file_name = row["file_path"]
    final_class_labels = row["label"]

    # MFCC özelliklerini çıkar
    data = features_extractor(file_name)

    if data is not None:
        extracted_features.append([*data, final_class_labels])

100%|██████████| 836/836 [00:09<00:00, 88.12it/s] 


In [17]:
# MFCC özelliklerini DataFrame'e dönüştür
features_df = pd.DataFrame(extracted_features, columns=[f'mfcc_{i+1}' for i in range(128)] + ['label'])

In [19]:
# Özellik ve etiketleri ayırma
X = features_df.drop(columns=['label'])
y = features_df['label']

# Model oluşturma.

In [22]:
# Eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [24]:
# MLPC modelini oluştur ve eğit
mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
mlp_model.fit(X_train, y_train)

MLPClassifier(max_iter=500, random_state=42)

In [26]:
# Tahmin yap
y_pred = mlp_model.predict(X_test)

In [28]:
# Sonuçları değerlendir
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
dogruluk = mlp_model.score(X_test, y_test)
print(f"Model doğruluğu: {dogruluk}")

[[57  0  0]
 [ 0 56  0]
 [ 0  0 55]]
              precision    recall  f1-score   support

      berkay       1.00      1.00      1.00        57
        ekin       1.00      1.00      1.00        56
       hakan       1.00      1.00      1.00        55

    accuracy                           1.00       168
   macro avg       1.00      1.00      1.00       168
weighted avg       1.00      1.00      1.00       168

Model doğruluğu: 1.0


In [30]:
print("Eğitim sınıfları:", np.unique(y_train))
print("Test sınıfları:", np.unique(y_test))
print("Tahmin edilen sınıflar:", np.unique(y_pred))

Eğitim sınıfları: ['berkay' 'ekin' 'hakan']
Test sınıfları: ['berkay' 'ekin' 'hakan']
Tahmin edilen sınıflar: ['berkay' 'ekin' 'hakan']


In [32]:
# Modeli diske kaydetme
model_save_directory = 'mlp_model.pkl'
joblib.dump(mlp_model, model_save_directory)

['mlp_model.pkl']

In [89]:
features_df

mfcc_1      mfcc_2     mfcc_3     mfcc_4     mfcc_5     mfcc_6  \
0   -508.488312  122.640045   4.909230  15.464577  12.381002  10.871942   
1   -371.310852  154.407654  -3.380808  49.665424  28.601027  30.412645   
2   -358.947876  172.150757 -10.851999  53.442532  31.055927  33.866016   
3   -330.505249  196.762802  -2.858322  34.840775  24.615166  21.043242   
4   -346.943176  150.719666  -8.315396  43.547424  18.597631  28.224108   
..          ...         ...        ...        ...        ...        ...   
831 -373.579437  155.518417  -0.751335  38.951473  14.234216   7.276370   
832 -369.010132  176.710587  15.503444  33.598385   9.089455   7.432762   
833 -415.220947  141.371246  14.878841  29.528095  13.416821   8.285192   
834 -466.275726  132.997192  39.905083  18.322664   4.664265  -3.298956   
835 -411.059448  126.524170  28.174917  31.626282  12.732472  10.934382   

        mfcc_7    mfcc_8     mfcc_9    mfcc_10  ...  mfcc_120  mfcc_121  \
0    10.303023  5.027215  -8.186682  -3.637561  ...  0.159044  0.120607   
1    11.529809 -0.391713 -13.333216  -8.397329  ... -0.416083  0.107544   
2    14.449401  2.202820  -5.977569 -12.640266  ... -0.226327 -0.416047   
3     4.593565  3.840230  -5.643089  -6.501838  ...  0.054150  0.066109   
4     8.434963  4.860088  -6.998712  -7.523575  ... -0.191850  0.197814   
..         ...       ...        ...        ...  ...       ...       ...   
831   7.848040 -2.299068   2.896512  -7.440723  ...  0.315973 -0.020341   
832   8.523851 -3.213322   6.503478  -6.435085  ...  0.122939 -0.177328   
833  13.164109 -8.225890  -0.669746  -4.463645  ...  0.167376 -0.563092   
834  -0.608142 -1.686559   1.504586  -4.792425  ...  0.467220 -0.108587   
835   9.882902 -8.979154   0.706503   0.266525  ...  0.296583 -0.546705   

     mfcc_122  mfcc_123  mfcc_124  mfcc_125  mfcc_126  mfcc_127  mfcc_128  \
0    0.002780 -0.244866 -0.115121  0.018163 -0.042575  0.023936  0.255041   
1    0.317084  0.088344 -0.136854  0.007253  0.427902  0.247950 -0.583718   
2    0.039067  1.288320 -0.633240  0.060403  0.286118  0.209307 -0.442361   
3   -0.255665  0.030659  0.237871  0.214907  0.014771  0.065306 -0.216160   
4   -0.185557  0.117092  0.337160  0.265549 -0.045660  0.027540 -0.524939   
..        ...       ...       ...       ...       ...       ...       ...   
831 -0.277388  0.100028  0.209395 -0.048636  0.174128  0.304188 -0.554973   
832 -0.244280  0.124687 -0.281800 -0.417231  0.278185  0.230449 -0.536705   
833 -0.203399  0.093099 -0.043566 -0.326890  0.150942  0.157925 -0.748294   
834 -0.087315 -0.191850 -0.081472 -0.127948  0.286347  0.183541 -0.120621   
835 -0.448634  0.332214 -0.425582 -0.006180  0.055982  0.404507 -0.568355   

           label  
0    berkay 7 dk  
1    berkay 7 dk  
2    berkay 7 dk  
3    berkay 7 dk  
4    berkay 7 dk  
..           ...  
831   hakan 7 dk  
832   hakan 7 dk  
833   hakan 7 dk  
834   hakan 7 dk  
835   hakan 7 dk  

[836 rows x 129 columns]